parameters:
    pk.config.adapter.ssm_client.class: PK\Config\StorageAdapter\AwsSsm
    pk.config.adapter.ssm_by_path_client.class: PK\Config\StorageAdapter\AwsSsmByPath
    pk.config.aws.ssm_client.class: Aws\Ssm\SsmClient
